spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1 from dual
      connection-timeout: 5000
      idle-timeout: 20000
      max-lifetime: 180000
      maximum-pool-size: 10
      minimum-idle: 3
    url: jdbc:mysql://192.168.1.13:3306/jeethink-crm?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 654321
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      # 上传文件最大为 200M
      max-file-size: 200MB
      # 上传请求最大为 300M
      max-request-size: 300MB
      location: D:/fileDownload
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#
#server:
#  port: 8445
#  http2:
#    # 启用http2
#    enabled: true
#  http:
#    port: 8082
#  ssl:
#    key-store: classpath:ams.p12
#    key-store-password: 123456
#    key-password: 123456
#    protocol: TLSv1.2 # 协议类型

debug: false

update:
  file:
    excelPath: d:/file/excel
